name: Build LaTeX documents
on:
  push:
    paths:
    - .github/workflows/build_tex.yml
    - tex/**

  pull_request:
    paths:
    - .github/workflows/build_tex.yml
    - tex/**

  workflow_dispatch:

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v4

    - name: Setup python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install Pygments
      run: |
        pip install Pygments

    - name: Compile LaTeX documents
      uses: xu-cheng/texlive-action/full@v1
      with:
        run: |
          cd tex/
          make pdf

    - name: Archive exercise files
      uses: actions/upload-artifact@v3
      with:
        name: tex-documents
        path: tex/**/*.pdf
